### ISSUE TITLE
Mensaje de Sesión Expirada

### ISSUE THREAD

**Issue by jforni** [MatheoSuch/JavaPet-Frontend#1]
Cuando ingreso al sitio me muestra el mensaje de Sesión Expirada y tengo que presionar el botón Iniciar sesión. Y sigue sucediendo en cada página a la que quiero revisar.
![image](https://github.com/user-attachments/assets/d8e7bf18-227a-4dc7-a2b4-670e665bfba9)

**Comment by MatheoSuch** [comment]
Issue solucionado
