### ISSUE TITLE
No se limpia formulario luego de enviarlo

### ISSUE THREAD

**Issue by jforni** [MatheoSuch/JavaPet-Frontend#2]
Cuando envío una consulta no se limpia el formulario.
Adjunto imagenes:
Cargo los datos
![image](https://github.com/user-attachments/assets/00fe8502-ce65-4cfe-a2df-cd9dabb3e33c)
Presiono el botón enviar
![image](https://github.com/user-attachments/assets/cf59d20b-a75d-4cb3-b058-6132b175aaeb)
El formulario sigue cargado
![image](https://github.com/user-attachments/assets/e7211c42-1f6d-4df6-b6f5-a0f7ed5a9f7c)

**Comment by MatheoSuch** [comment]
Issue solucionado

**Comment by MatheoSuch** [comment]
![image](https://github.com/user-attachments/assets/64c7c54e-000f-4fa1-b0f3-8a7061e1340b)
