### ISSUE TITLE
Intento loguearme sin estar registrado y no muestra ningún mensaje de error

### ISSUE THREAD

**Issue by jforni** [MatheoSuch/JavaPet-Frontend#3]
Cuando intento loguearme sin estar registrado no me muestra ningún mensaje de error o de que debería registrarme.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/1402182f-207c-44b6-8fa3-76ff725e1720)

**Comment by MatheoSuch** [comment]
![prueba mensaje](https://github.com/user-attachments/assets/ff81c0f9-c759-4990-88cc-719b6b7fcf6a)
El modal tarda en aparecer al comienzo, creo que es por los tiempos que toma la base de datos en confirmar que es incorrecto o no esta ahi.
