### ISSUE TITLE
Tamaños de imagenes diferentes

### ISSUE THREAD

**Issue by jforni** [MatheoSuch/JavaPet-Frontend#4]
En el carrusel de Nuestros Productos, hay imágenes de diferentes tamaños.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/b2374d45-9ade-4b00-9b13-93ca73ebcfd1)

**Comment by MatheoSuch** [comment]
Ajuste el tamaño de las card en pantallas de tamaño pequeño para que sean iguales, supongo que no hay problema del tamaño de las propias iamgenes de bolsas de alimentos ya que se tratan de distintos pesos y formas. Adjunto correción y demas ejemplos que sirvio como referencia del tamaño. 
![image](https://github.com/user-attachments/assets/ea4d14af-fee0-4ba8-9560-1f219b78daf1)

**Comment by MatheoSuch** [comment]
![ejmplo bolsas](https://github.com/user-attachments/assets/85dd0784-5aa0-4acc-8e88-879e904a9b82)
