### ISSUE TITLE
Ver planes de salud

### ISSUE THREAD

**Issue by jforni** [MatheoSuch/JavaPet-Frontend#5]
Cuando selecciono para ver un plan de salud, me lleva a la pagina de Planes de salud, pero a la parte inferior de la página, me debería llevar y mostrar el plan seleccionado.
Adjunto imagen:
Selecciono un plan
![image](https://github.com/user-attachments/assets/8b11acfe-9086-4e44-b3cf-16e4941fd735)
Lo que me muestra cuando selecciono un plan:
![image](https://github.com/user-attachments/assets/703c6930-0d67-4420-924f-3a60a3327e94)

**Comment by MatheoSuch** [comment]
Issue solucionado
