### ISSUE TITLE
Usuario Admin tiene la posibilidad de editarse

### ISSUE THREAD

**Issue by jforni** [MatheoSuch/JavaPet-Frontend#6]
En el panel de usuarios del Administrador, en la tabla de usuarios, me muestra los datos del Usuario Admin, y la opción de editar el rol, si  se cambia ese dato nos quedamos sin Admin.
![image](https://github.com/user-attachments/assets/17b95ffd-3ae6-4da2-a7f9-53d8d849ad40)

**Comment by MatheoSuch** [comment]
Issue solucionado, los botones de eliminar y editar en caso de que solo haya 1 admin estan inhabilitados para ese usaurio (de rol admin).
